config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "rankings#index"
  resources :users, only: [:edit, :update]
  resources :rankings, only: [:new, :create]
end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ranking.rb
class Ranking < ApplicationRecord
  has_many :ranking_users
  has_many :users, through: :ranking_users

  validates :title,    presence: true
  validates :category, presence: true
  validates :choice_a, presence: true 
  validates :choice_b, presence: true 

end

app/models/ranking_user.rb
class RankingUser < ApplicationRecord
  belongs_to :ranking
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true

  has_many :ranking_users
  has_many :rankings, through: :ranking_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/rankings_controller.rb
class RankingsController < ApplicationController
  
  def index
  end
  
  def new
    @ranking = Ranking.new
  end

  def create
    @ranking = Ranking.new(ranking_params)
    if @ranking.save
      redirect_to root_path
    else
      render :new
    end
  end

  private
  def ranking_params
    params.require(:ranking).permit(:title, :category, :choice_a, :choice_b, :choice_c, :choice_d, :choice_e, user_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email)
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def index
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rankings_helper.rb
module RankingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppRank</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rankings/index.html.erb
<div class='wrapper'>
  <div class='side-bar'>
    <%= render "votes/side_bar" %>
  </div>
</div>

app/views/rankings/new.html.erb
<div class='chat-ranking-form'>
  <h1>新規ランキング</h1>
  <%=form_with model: @ranking, local: true do |f|%>
    
    <div class='chat-ranking-form__field'>
      <div class='chat-ranking-form__field--left'>
        <%= f.label :ランキング名, class: 'chat-ranking-form__label'%>
      </div>
      <div class='chat-ranking-form__field--right'>
        <%= f.text_field :title, class: 'chat__ranking_name chat-ranking-form__input', placeholder: 'ランキング名を入力してください'%>
      </div>
    </div>

    <div class='chat-ranking-form__field'>
      <div class='chat-ranking-form__field--left'>
        <%= f.label :カテゴリ名, class: 'chat-ranking-form__label'%>
      </div>
      <div class='chat-ranking-form__field--right'>
        <%= f.text_field :category, class: 'chat__ranking_name chat-ranking-form__input', placeholder: 'カテゴリ名を入力してください'%>
      </div>
    </div>

    <div class='chat-ranking-form__field'>
      <div class='chat-ranking-form__field--left'>
        <%= f.label :選択1, class: 'chat-ranking-form__label'%>
      </div>
      <div class='chat-ranking-form__field--right'>
        <%= f.text_field :choice_a, class: 'chat__ranking_name chat-ranking-form__input', placeholder: '選択1を入力してください'%>
      </div>
    </div>

    <div class='chat-ranking-form__field'>
      <div class='chat-ranking-form__field--left'>
        <%= f.label :選択2, class: 'chat-ranking-form__label'%>
      </div>
      <div class='chat-ranking-form__field--right'>
        <%= f.text_field :choice_b, class: 'chat__ranking_name chat-ranking-form__input', placeholder: '選択2を入力してください'%>
      </div>
    </div>

    <div class='chat-ranking-form__field'>
      <div class='chat-ranking-form__field--left'>
        <%= f.label :選択3, class: 'chat-ranking-form__label'%>
      </div>
      <div class='chat-ranking-form__field--right'>
        <%= f.text_field :choice_c, class: 'chat__ranking_name chat-ranking-form__input', placeholder: '選択3を入力してください'%>
      </div>
    </div>

    <div class='chat-ranking-form__field'>
      <div class='chat-ranking-form__field--left'>
        <%= f.label :選択4, class: 'chat-ranking-form__label'%>
      </div>
      <div class='chat-ranking-form__field--right'>
        <%= f.text_field :choice_d, class: 'chat__ranking_name chat-ranking-form__input', placeholder: '選択4を入力してください'%>
      </div>
    </div>

    <div class='chat-ranking-form__field'>
      <div class='chat-ranking-form__field--left'>
        <%= f.label :選択5, class: 'chat-ranking-form__label'%>
      </div>
      <div class='chat-ranking-form__field--right'>
        <%= f.text_field :choice_e, class: 'chat__ranking_name chat-ranking-form__input', placeholder: '選択5を入力してください'%>
      </div>
    </div>

    <div class='chat-ranking-form__field'>
      <div class='chat-ranking-form__field--right'>
        <%= f.submit class: 'chat-ranking-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'%>
      <%= link_to "チャットページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>  
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :nickname%>
          </div>
          <div class='field-input'>
            <%= f.text_field :nickname, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/votes/_main_chat.html.erb
＜サイドバー＞

app/views/votes/_main_rank.html.erb
<div class="rank-header">
  <div class="left-header">
    <div class="header-title">
      hogefuga
    </div>
  </div>
  <div class="right-header">
    <div class="header-button">
      <a href="#">投票を終了する</a>
    </div>
  </div>
</div>

<div class="votes">
  <div class="vote">
    <div class="upper-vote">
      <div class="vote-user">
        Tom
      </div>
      <div class="vote-date">
        2020/3/31(Wed) 12:43:30
      </div>
    </div>
    <div class="lower-vote">
      <div class="vote-content">
        おはよう
      </div>
    </div>
  </div>

  <div class="vote">
    <div class="upper-vote">
      <div class="vote-user">
        Tom
      </div>
      <div class="vote-date">
        2020/3/31(Wed) 12:47:30
      </div>
    </div>
    <div class="lower-vote">
      <div class="vote-content">
        こんばんは
      </div>
    </div>
  </div>
</div>

<div class="form">
  <div class="form-input">
    <input class="form-vote" placeholder= "ranking a message">
  </div>
  <input class="form-submit" type="submit" value="送信">
</div>  

app/views/votes/_side_bar.html.erb
<div class="side-bar-header">
  <div class="header-name">
    <%= link_to current_user.nickname, edit_user_path(current_user) %>
  </div>
  <div class="create-ranking">
    <%= link_to "ランキングを作成する", new_ranking_path %>
  </div>
</div>

<div class="rankings">
  <% current_user.rankings.each do |ranking| %>
    <div class="ranking">
      <div class="ranking-name">
        <a href="#"><%= ranking.title %></a>
      </div>
    </div>
  <% end %>
</div>

app/views/votes/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "side_bar" %>
  </div>
  <div class="rank">
    <%= render "main_rank" %>
  </div>
</div>